name: Build and Deploy on gh-pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Install dependecies
              run: npm ci
            - name: Install gh-pages
              run: npm install gh-pages
            - name: deploy
              run: npm run deploy
