name: deploy test
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  predeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
  deploy:
    runs-on: ubuntu-latest
    needs: predeploy
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
        env: 
          CI: false
      - run: git config user.email "gaga63354@gmail.com"
      - run: git config user.name "Rayman-bat9"
      - run: npm ci
      - name: Deploy
        run: npm run deploy
